<?php

namespace Cloudcogs\PayPal\Support;

/**
 * The PayPal REST APIs accept the following state and province codes in the state parameter for an address.
 *
 * @see https://developer.paypal.com/api/rest/reference/state-codes/
 */
class StateCodes
{
    protected static array $data = [
        'AR' => [
            ['Name' => 'Buenos Aires (Ciudad)', 'Code' => 'CIUDAD AUTÓNOMA DE BUENOS AIRES'],
            ['Name' => 'Buenos Aires (Provincia)', 'Code' => 'BUENOS AIRES'],
            ['Name' => 'Catamarca', 'Code' => 'CATAMARCA'],
            ['Name' => 'Chaco', 'Code' => 'CHACO'],
            ['Name' => 'Chubut', 'Code' => 'CHUBUT'],
            ['Name' => 'Corrientes', 'Code' => 'CORRIENTES'],
            ['Name' => 'Córdoba', 'Code' => 'CÓRDOBA'],
            ['Name' => 'Entre Ríos', 'Code' => 'ENTRE RÍOS'],
            ['Name' => 'Formosa', 'Code' => 'FORMOSA'],
            ['Name' => 'Jujuy', 'Code' => 'JUJUY'],
            ['Name' => 'La Pampa', 'Code' => 'LA PAMPA'],
            ['Name' => 'La Rioja', 'Code' => 'LA RIOJA'],
            ['Name' => 'Mendoza', 'Code' => 'MENDOZA'],
            ['Name' => 'Misiones', 'Code' => 'MISIONES'],
            ['Name' => 'Neuquén', 'Code' => 'NEUQUÉN'],
            ['Name' => 'Río Negro', 'Code' => 'RÍO NEGRO'],
            ['Name' => 'Salta', 'Code' => 'SALTA'],
            ['Name' => 'San Juan', 'Code' => 'SAN JUAN'],
            ['Name' => 'San Luis', 'Code' => 'SAN LUIS'],
            ['Name' => 'Santa Cruz', 'Code' => 'SANTA CRUZ'],
            ['Name' => 'Santa Fe', 'Code' => 'SANTA FE'],
            ['Name' => 'Santiago del Estero', 'Code' => 'SANTIAGO DEL ESTERO'],
            ['Name' => 'Tierra del Fuego', 'Code' => 'TIERRA DEL FUEGO'],
            ['Name' => 'Tucumán', 'Code' => 'TUCUMÁN'],
        ],
        'BR' => [
            ['Name' => 'Acre', 'Code' => 'AC'],
            ['Name' => 'Alagoas', 'Code' => 'AL'],
            ['Name' => 'Amapá', 'Code' => 'AP'],
            ['Name' => 'Amazonas', 'Code' => 'AM'],
            ['Name' => 'Bahia', 'Code' => 'BA'],
            ['Name' => 'Ceará', 'Code' => 'CE'],
            ['Name' => 'Distrito Federal', 'Code' => 'DF'],
            ['Name' => 'Espírito Santo', 'Code' => 'ES'],
            ['Name' => 'Goiás', 'Code' => 'GO'],
            ['Name' => 'Maranhão', 'Code' => 'MA'],
            ['Name' => 'Mato Grosso', 'Code' => 'MT'],
            ['Name' => 'Mato Grosso do Sul', 'Code' => 'MS'],
            ['Name' => 'Minas Gerais', 'Code' => 'MG'],
            ['Name' => 'Paraná', 'Code' => 'PR'],
            ['Name' => 'Paraíba', 'Code' => 'PB'],
            ['Name' => 'Pará', 'Code' => 'PA'],
            ['Name' => 'Pernambuco', 'Code' => 'PE'],
            ['Name' => 'Piauí', 'Code' => 'PI'],
            ['Name' => 'Rio Grande do Norte', 'Code' => 'RN'],
            ['Name' => 'Rio Grande do Sul', 'Code' => 'RS'],
            ['Name' => 'Rio de Janeiro', 'Code' => 'RJ'],
            ['Name' => 'Rondônia', 'Code' => 'RO'],
            ['Name' => 'Roraima', 'Code' => 'RR'],
            ['Name' => 'Santa Catarina', 'Code' => 'SC'],
            ['Name' => 'Sergipe', 'Code' => 'SE'],
            ['Name' => 'São Paulo', 'Code' => 'SP'],
            ['Name' => 'Tocantins', 'Code' => 'TO'],
        ],
        'CA' => [
            ['Name' => 'Alberta', 'Code' => 'AB'],
            ['Name' => 'British Columbia', 'Code' => 'BC'],
            ['Name' => 'Manitoba', 'Code' => 'MB'],
            ['Name' => 'New Brunswick', 'Code' => 'NB'],
            ['Name' => 'Newfoundland and Labrador', 'Code' => 'NL'],
            ['Name' => 'Northwest Territories', 'Code' => 'NT'],
            ['Name' => 'Nova Scotia', 'Code' => 'NS'],
            ['Name' => 'Nunavut', 'Code' => 'NU'],
            ['Name' => 'Ontario', 'Code' => 'ON'],
            ['Name' => 'Prince Edward Island', 'Code' => 'PE'],
            ['Name' => 'Quebec', 'Code' => 'QC'],
            ['Name' => 'Saskatchewan', 'Code' => 'SK'],
            ['Name' => 'Yukon', 'Code' => 'YT'],
        ],
        'C2' => [
            ['Name' => 'Anhui Sheng', 'Code' => 'CN-AH'],
            ['Name' => 'Beijing Shi', 'Code' => 'CN-BJ'],
            ['Name' => 'Chongqing Shi', 'Code' => 'CN-CQ'],
            ['Name' => 'Fujian Sheng', 'Code' => 'CN-FJ'],
            ['Name' => 'Guangdong Sheng', 'Code' => 'CN-GD'],
            ['Name' => 'Gansu Sheng', 'Code' => 'CN-GS'],
            ['Name' => 'Guangxi Zhuangzu Zizhiqu', 'Code' => 'CN-GX'],
            ['Name' => 'Guizhou Sheng', 'Code' => 'CN-GZ'],
            ['Name' => 'Henan Sheng', 'Code' => 'CN-HA'],
            ['Name' => 'Hubei Sheng', 'Code' => 'CN-HB'],
            ['Name' => 'Hebei Sheng', 'Code' => 'CN-HE'],
            ['Name' => 'Hainan Sheng', 'Code' => 'CN-HI'],
            ['Name' => 'Hong Kong SAR (en)', 'Code' => 'CN-HK'],
            ['Name' => 'Xianggang Tebiexingzhengqu (zh)', 'Code' => ''],
            ['Name' => 'Heilongjiang Sheng', 'Code' => 'CN-HL'],
            ['Name' => 'Hunan Sheng', 'Code' => 'CN-HN'],
            ['Name' => 'Jilin Sheng', 'Code' => 'CN-JL'],
            ['Name' => 'Jiangsu Sheng', 'Code' => 'CN-JS'],
            ['Name' => 'Jiangxi Sheng', 'Code' => 'CN-JX'],
            ['Name' => 'Liaoning Sheng', 'Code' => 'CN-LN'],
            ['Name' => 'Macao SAR (en)', 'Code' => 'CN-MO'],
            ['Name' => 'Macau SAR (pt)', 'Code' => ''],
            ['Name' => 'Aomen Tebiexingzhengqu (zh)', 'Code' => ''],
            ['Name' => 'Nei Mongol Zizhiqu (mn)', 'Code' => 'CN-NM'],
            ['Name' => 'Ningxia Huizu Zizhiqu', 'Code' => 'CN-NX'],
            ['Name' => 'Qinghai Sheng', 'Code' => 'CN-QH'],
            ['Name' => 'Sichuan Sheng', 'Code' => 'CN-SC'],
            ['Name' => 'Shandong Sheng', 'Code' => 'CN-SD'],
            ['Name' => 'Shanghai Shi', 'Code' => 'CN-SH'],
            ['Name' => 'Shaanxi Sheng', 'Code' => 'CN-SN'],
            ['Name' => 'Shanxi Sheng', 'Code' => 'CN-SX'],
            ['Name' => 'Tianjin Shi', 'Code' => 'CN-TJ'],
            ['Name' => 'Taiwan Sheng', 'Code' => 'CN-TW'],
            ['Name' => 'Xinjiang Uygur Zizhiqu', 'Code' => 'CN-XJ'],
            ['Name' => 'Xizang Zizhiqu', 'Code' => 'CN-XZ'],
            ['Name' => 'Yunnan Sheng', 'Code' => 'CN-YN'],
            ['Name' => 'Zhejiang Sheng', 'Code' => 'CN-ZJ'],
        ],
        'IN' => [
            ['Name' => 'Andaman and Nicobar Islands', 'Code' => 'Andaman and Nicobar Islands'],
            ['Name' => 'Andhra Pradesh', 'Code' => 'Andhra Pradesh'],
            ['Name' => 'Army Post Office', 'Code' => 'APO'],
            ['Name' => 'Arunachal Pradesh', 'Code' => 'Arunachal Pradesh'],
            ['Name' => 'Assam', 'Code' => 'Assam'],
            ['Name' => 'Bihar', 'Code' => 'Bihar'],
            ['Name' => 'Chandigarh', 'Code' => 'Chandigarh'],
            ['Name' => 'Chhattisgarh', 'Code' => 'Chhattisgarh'],
            ['Name' => 'Dadra and Nagar Haveli', 'Code' => 'Dadra and Nagar Haveli'],
            ['Name' => 'Daman and Diu', 'Code' => 'Daman and Diu'],
            ['Name' => 'Delhi', 'Code' => 'Delhi (NCT)'],
            ['Name' => 'Goa', 'Code' => 'Goa'],
            ['Name' => 'Gujarat', 'Code' => 'Gujarat'],
            ['Name' => 'Haryana', 'Code' => 'Haryana'],
            ['Name' => 'Himachal Pradesh', 'Code' => 'Himachal Pradesh'],
            ['Name' => 'Jammu and Kashmir', 'Code' => 'Jammu and Kashmir'],
            ['Name' => 'Jharkhand', 'Code' => 'Jharkhand'],
            ['Name' => 'Karnataka', 'Code' => 'Karnataka'],
            ['Name' => 'Kerala', 'Code' => 'Kerala'],
            ['Name' => 'Lakshadweep', 'Code' => 'Lakshadweep'],
            ['Name' => 'Madhya Pradesh', 'Code' => 'Madhya Pradesh'],
            ['Name' => 'Maharashtra', 'Code' => 'Maharashtra'],
            ['Name' => 'Manipur', 'Code' => 'Manipur'],
            ['Name' => 'Meghalaya', 'Code' => 'Meghalaya'],
            ['Name' => 'Mizoram', 'Code' => 'Mizoram'],
            ['Name' => 'Nagaland', 'Code' => 'Nagaland'],
            ['Name' => 'Odisha', 'Code' => 'Odisha'],
            ['Name' => 'Puducherry', 'Code' => 'Puducherry'],
            ['Name' => 'Punjab', 'Code' => 'Punjab'],
            ['Name' => 'Rajasthan', 'Code' => 'Rajasthan'],
            ['Name' => 'Sikkim', 'Code' => 'Sikkim'],
            ['Name' => 'Tamil Nadu', 'Code' => 'Tamil Nadu'],
            ['Name' => 'Telangana', 'Code' => 'Telangana'],
            ['Name' => 'Tripura', 'Code' => 'Tripura'],
            ['Name' => 'Uttar Pradesh', 'Code' => 'Uttar Pradesh'],
            ['Name' => 'Uttarakhand', 'Code' => 'Uttarakhand'],
            ['Name' => 'West Bengal', 'Code' => 'West Bengal'],
        ],
        'ID' => [
            ['Name' => 'Bali', 'Code' => 'ID-BA'],
            ['Name' => 'Bangka Belitung', 'Code' => 'ID-BB'],
            ['Name' => 'Banten', 'Code' => 'ID-BT'],
            ['Name' => 'Bengkulu', 'Code' => 'ID-BE'],
            ['Name' => 'DI Yogyakarta', 'Code' => 'ID-YO'],
            ['Name' => 'DKI Jakarta', 'Code' => 'ID-JK'],
            ['Name' => 'Gorontalo', 'Code' => 'ID-GO'],
            ['Name' => 'Jambi', 'Code' => 'ID-JA'],
            ['Name' => 'Jawa Barat', 'Code' => 'ID-JB'],
            ['Name' => 'Jawa Tengah', 'Code' => 'ID-JT'],
            ['Name' => 'Jawa Timur', 'Code' => 'ID-JI'],
            ['Name' => 'Kalimantan Barat', 'Code' => 'ID-KB'],
            ['Name' => 'Kalimantan Selatan', 'Code' => 'ID-KS'],
            ['Name' => 'Kalimantan Tengah', 'Code' => 'ID-KT'],
            ['Name' => 'Kalimantan Timur', 'Code' => 'ID-KI'],
            ['Name' => 'Kalimantan Utara', 'Code' => 'ID-KU'],
            ['Name' => 'Kepulauan Riau', 'Code' => 'ID-KR'],
            ['Name' => 'Lampung', 'Code' => 'ID-LA'],
            ['Name' => 'Maluku', 'Code' => 'ID-MA'],
            ['Name' => 'Maluku Utara', 'Code' => 'ID-MU'],
            ['Name' => 'Nanggroe Aceh Darussalam', 'Code' => 'ID-AC'],
            ['Name' => 'Nusa Tenggara Barat', 'Code' => 'ID-NB'],
            ['Name' => 'Nusa Tenggara Timur', 'Code' => 'ID-NT'],
            ['Name' => 'Papua', 'Code' => 'ID-PA'],
            ['Name' => 'Papua Barat', 'Code' => 'ID-PB'],
            ['Name' => 'Riau', 'Code' => 'ID-RI'],
            ['Name' => 'Sulawesi Barat', 'Code' => 'ID-SR'],
            ['Name' => 'Sulawesi Selatan', 'Code' => 'ID-SN'],
            ['Name' => 'Sulawesi Tengah', 'Code' => 'ID-ST'],
            ['Name' => 'Sulawesi Tenggara', 'Code' => 'ID-SG'],
            ['Name' => 'Sulawesi Utara', 'Code' => 'ID-SA'],
            ['Name' => 'Sumatera Barat', 'Code' => 'ID-SB'],
            ['Name' => 'Sumatera Selatan', 'Code' => 'ID-SS'],
            ['Name' => 'Sumatera Utara', 'Code' => 'ID-SU'],
        ],
        'IT' => [
            ['Name' => 'Agrigento', 'Code' => 'AG'],
            ['Name' => 'Alessandria', 'Code' => 'AL'],
            ['Name' => 'Ancona', 'Code' => 'AN'],
            ['Name' => 'Aosta', 'Code' => 'AO'],
            ['Name' => 'Arezzo', 'Code' => 'AR'],
            ['Name' => 'Ascoli Piceno', 'Code' => 'AP'],
            ['Name' => 'Asti', 'Code' => 'AT'],
            ['Name' => 'Avellino', 'Code' => 'AV'],
            ['Name' => 'Bari', 'Code' => 'BA'],
            ['Name' => 'Barletta-Andria-Trani', 'Code' => 'BT'],
            ['Name' => 'Belluno', 'Code' => 'BL'],
            ['Name' => 'Benevento', 'Code' => 'BN'],
            ['Name' => 'Bergamo', 'Code' => 'BG'],
            ['Name' => 'Biella', 'Code' => 'BI'],
            ['Name' => 'Bologna', 'Code' => 'BO'],
            ['Name' => 'Bolzano', 'Code' => 'BZ'],
            ['Name' => 'Brescia', 'Code' => 'BS'],
            ['Name' => 'Brindisi', 'Code' => 'BR'],
            ['Name' => 'Cagliari', 'Code' => 'CA'],
            ['Name' => 'Caltanissetta', 'Code' => 'CL'],
            ['Name' => 'Campobasso', 'Code' => 'CB'],
            ['Name' => 'Carbonia-Iglesias', 'Code' => 'CI'],
            ['Name' => 'Caserta', 'Code' => 'CE'],
            ['Name' => 'Catania', 'Code' => 'CT'],
            ['Name' => 'Catanzaro', 'Code' => 'CZ'],
            ['Name' => 'Chieti', 'Code' => 'CH'],
            ['Name' => 'Como', 'Code' => 'CO'],
            ['Name' => 'Cosenza', 'Code' => 'CS'],
            ['Name' => 'Cremona', 'Code' => 'CR'],
            ['Name' => 'Crotone', 'Code' => 'KR'],
            ['Name' => 'Cuneo', 'Code' => 'CN'],
            ['Name' => 'Enna', 'Code' => 'EN'],
            ['Name' => 'Fermo', 'Code' => 'FM'],
            ['Name' => 'Ferrara', 'Code' => 'FE'],
            ['Name' => 'Firenze', 'Code' => 'FI'],
            ['Name' => 'Foggia', 'Code' => 'FG'],
            ['Name' => 'Forlì-Cesena', 'Code' => 'FC'],
            ['Name' => 'Frosinone', 'Code' => 'FR'],
            ['Name' => 'Genova', 'Code' => 'GE'],
            ['Name' => 'Gorizia', 'Code' => 'GO'],
            ['Name' => 'Grosseto', 'Code' => 'GR'],
            ['Name' => 'Imperia', 'Code' => 'IM'],
            ['Name' => 'Isernia', 'Code' => 'IS'],
            ['Name' => 'L\'Aquila', 'Code' => 'AQ'],
            ['Name' => 'La Spezia', 'Code' => 'SP'],
            ['Name' => 'Latina', 'Code' => 'LT'],
            ['Name' => 'Lecce', 'Code' => 'LE'],
            ['Name' => 'Lecco', 'Code' => 'LC'],
            ['Name' => 'Livorno', 'Code' => 'LI'],
            ['Name' => 'Lodi', 'Code' => 'LO'],
            ['Name' => 'Lucca', 'Code' => 'LU'],
            ['Name' => 'Macerata', 'Code' => 'MC'],
            ['Name' => 'Mantova', 'Code' => 'MN'],
            ['Name' => 'Massa-Carrara', 'Code' => 'MS'],
            ['Name' => 'Matera', 'Code' => 'MT'],
            ['Name' => 'Medio Campidano', 'Code' => 'VS'],
            ['Name' => 'Messina', 'Code' => 'ME'],
            ['Name' => 'Milano', 'Code' => 'MI'],
            ['Name' => 'Modena', 'Code' => 'MO'],
            ['Name' => 'Monza e della Brianza', 'Code' => 'MB'],
            ['Name' => 'Napoli', 'Code' => 'NA'],
            ['Name' => 'Novara', 'Code' => 'NO'],
            ['Name' => 'Nuoro', 'Code' => 'NU'],
            ['Name' => 'Ogliastra', 'Code' => 'OG'],
            ['Name' => 'Olbia-Tempio', 'Code' => 'OT'],
            ['Name' => 'Oristano', 'Code' => 'OR'],
            ['Name' => 'Padova', 'Code' => 'PD'],
            ['Name' => 'Palermo', 'Code' => 'PA'],
            ['Name' => 'Parma', 'Code' => 'PR'],
            ['Name' => 'Pavia', 'Code' => 'PV'],
            ['Name' => 'Perugia', 'Code' => 'PG'],
            ['Name' => 'Pesaro e Urbino', 'Code' => 'PU'],
            ['Name' => 'Pescara', 'Code' => 'PE'],
            ['Name' => 'Piacenza', 'Code' => 'PC'],
            ['Name' => 'Pisa', 'Code' => 'PI'],
            ['Name' => 'Pistoia', 'Code' => 'PT'],
            ['Name' => 'Pordenone', 'Code' => 'PN'],
            ['Name' => 'Potenza', 'Code' => 'PZ'],
            ['Name' => 'Prato', 'Code' => 'PO'],
            ['Name' => 'Ragusa', 'Code' => 'RG'],
            ['Name' => 'Ravenna', 'Code' => 'RA'],
            ['Name' => 'Reggio Calabria', 'Code' => 'RC'],
            ['Name' => 'Reggio Emilia', 'Code' => 'RE'],
            ['Name' => 'Rieti', 'Code' => 'RI'],
            ['Name' => 'Rimini', 'Code' => 'RN'],
            ['Name' => 'Roma', 'Code' => 'RM'],
            ['Name' => 'Rovigo', 'Code' => 'RO'],
            ['Name' => 'Salerno', 'Code' => 'SA'],
            ['Name' => 'Sassari', 'Code' => 'SS'],
            ['Name' => 'Savona', 'Code' => 'SV'],
            ['Name' => 'Siena', 'Code' => 'SI'],
            ['Name' => 'Siracusa', 'Code' => 'SR'],
            ['Name' => 'Sondrio', 'Code' => 'SO'],
            ['Name' => 'Taranto', 'Code' => 'TA'],
            ['Name' => 'Teramo', 'Code' => 'TE'],
            ['Name' => 'Terni', 'Code' => 'TR'],
            ['Name' => 'Torino', 'Code' => 'TO'],
            ['Name' => 'Trapani', 'Code' => 'TP'],
            ['Name' => 'Trento', 'Code' => 'TN'],
            ['Name' => 'Treviso', 'Code' => 'TV'],
            ['Name' => 'Trieste', 'Code' => 'TS'],
            ['Name' => 'Udine', 'Code' => 'UD'],
            ['Name' => 'Varese', 'Code' => 'VA'],
            ['Name' => 'Venezia', 'Code' => 'VE'],
            ['Name' => 'Verbano-Cusio-Ossola', 'Code' => 'VB'],
            ['Name' => 'Vercelli', 'Code' => 'VC'],
            ['Name' => 'Verona', 'Code' => 'VR'],
            ['Name' => 'Vibo Valentia', 'Code' => 'VV'],
            ['Name' => 'Vicenza', 'Code' => 'VI'],
            ['Name' => 'Viterbo', 'Code' => 'VT'],
        ],
        'JP' => [
            ['Name' => 'Aichi', 'Code' => 'AICHI-KEN'],
            ['Name' => 'Akita', 'Code' => 'AKITA-KEN'],
            ['Name' => 'Aomori', 'Code' => 'AOMORI-KEN'],
            ['Name' => 'Chiba', 'Code' => 'CHIBA-KEN'],
            ['Name' => 'Ehime', 'Code' => 'EHIME-KEN'],
            ['Name' => 'Fukui', 'Code' => 'FUKUI-KEN'],
            ['Name' => 'Fukuoka', 'Code' => 'FUKUOKA-KEN'],
            ['Name' => 'Fukushima', 'Code' => 'FUKUSHIMA-KEN'],
            ['Name' => 'Gifu', 'Code' => 'GIFU-KEN'],
            ['Name' => 'Gunma', 'Code' => 'GUNMA-KEN'],
            ['Name' => 'Hiroshima', 'Code' => 'HIROSHIMA-KEN'],
            ['Name' => 'Hokkaido', 'Code' => 'HOKKAIDO'],
            ['Name' => 'Hyogo', 'Code' => 'HYOGO-KEN'],
            ['Name' => 'Ibaraki', 'Code' => 'IBARAKI-KEN'],
            ['Name' => 'Ishikawa', 'Code' => 'ISHIKAWA-KEN'],
            ['Name' => 'Iwate', 'Code' => 'IWATE-KEN'],
            ['Name' => 'Kagawa', 'Code' => 'KAGAWA-KEN'],
            ['Name' => 'Kagoshima', 'Code' => 'KAGOSHIMA-KEN'],
            ['Name' => 'Kanagawa', 'Code' => 'KANAGAWA-KEN'],
            ['Name' => 'Kochi', 'Code' => 'KOCHI-KEN'],
            ['Name' => 'Kumamoto', 'Code' => 'KUMAMOTO-KEN'],
            ['Name' => 'Kyoto', 'Code' => 'KYOTO-FU'],
            ['Name' => 'Mie', 'Code' => 'MIE-KEN'],
            ['Name' => 'Miyagi', 'Code' => 'MIYAGI-KEN'],
            ['Name' => 'Miyazaki', 'Code' => 'MIYAZAKI-KEN'],
            ['Name' => 'Nagano', 'Code' => 'NAGANO-KEN'],
            ['Name' => 'Nagasaki', 'Code' => 'NAGASAKI-KEN'],
            ['Name' => 'Nara', 'Code' => 'NARA-KEN'],
            ['Name' => 'Niigata', 'Code' => 'NIIGATA-KEN'],
            ['Name' => 'Oita', 'Code' => 'OITA-KEN'],
            ['Name' => 'Okayama', 'Code' => 'OKAYAMA-KEN'],
            ['Name' => 'Okinawa', 'Code' => 'OKINAWA-KEN'],
            ['Name' => 'Osaka', 'Code' => 'OSAKA-FU'],
            ['Name' => 'Saga', 'Code' => 'SAGA-KEN'],
            ['Name' => 'Saitama', 'Code' => 'SAITAMA-KEN'],
            ['Name' => 'Shiga', 'Code' => 'SHIGA-KEN'],
            ['Name' => 'Shimane', 'Code' => 'SHIMANE-KEN'],
            ['Name' => 'Shizuoka', 'Code' => 'SHIZUOKA-KEN'],
            ['Name' => 'Tochigi', 'Code' => 'TOCHIGI-KEN'],
            ['Name' => 'Tokushima', 'Code' => 'TOKUSHIMA-KEN'],
            ['Name' => 'Tokyo', 'Code' => 'TOKYO-TO'],
            ['Name' => 'Tottori', 'Code' => 'TOTTORI-KEN'],
            ['Name' => 'Toyama', 'Code' => 'TOYAMA-KEN'],
            ['Name' => 'Wakayama', 'Code' => 'WAKAYAMA-KEN'],
            ['Name' => 'Yamagata', 'Code' => 'YAMAGATA-KEN'],
            ['Name' => 'Yamaguchi', 'Code' => 'YAMAGUCHI-KEN'],
            ['Name' => 'Yamanashi', 'Code' => 'YAMANASHI-KEN'],
        ],
        'MX' => [
            ['Name' => 'Aguascalientes', 'Code' => 'AGS'],
            ['Name' => 'Baja California', 'Code' => 'BC'],
            ['Name' => 'Baja California Sur', 'Code' => 'BCS'],
            ['Name' => 'Campeche', 'Code' => 'CAMP'],
            ['Name' => 'Chiapas', 'Code' => 'CHIS'],
            ['Name' => 'Chihuahua', 'Code' => 'CHIH'],
            ['Name' => 'Ciudad de México', 'Code' => 'CDMX'],
            ['Name' => 'Coahuila', 'Code' => 'COAH'],
            ['Name' => 'Colima', 'Code' => 'COL'],
            ['Name' => 'Distrito Federal', 'Code' => 'DF'],
            ['Name' => 'Durango', 'Code' => 'DGO'],
            ['Name' => 'Estado de México', 'Code' => 'MEX'],
            ['Name' => 'Guanajuato', 'Code' => 'GTO'],
            ['Name' => 'Guerrero', 'Code' => 'GRO'],
            ['Name' => 'Hidalgo', 'Code' => 'HGO'],
            ['Name' => 'Jalisco', 'Code' => 'JAL'],
            ['Name' => 'Michoacán', 'Code' => 'MICH'],
            ['Name' => 'Morelos', 'Code' => 'MOR'],
            ['Name' => 'Nayarit', 'Code' => 'NAY'],
            ['Name' => 'Nuevo León', 'Code' => 'NL'],
            ['Name' => 'Oaxaca', 'Code' => 'OAX'],
            ['Name' => 'Puebla', 'Code' => 'PUE'],
            ['Name' => 'Querétaro', 'Code' => 'QRO'],
            ['Name' => 'Quintana Roo', 'Code' => 'Q ROO'],
            ['Name' => 'San Luis Potosí', 'Code' => 'SLP'],
            ['Name' => 'Sinaloa', 'Code' => 'SIN'],
            ['Name' => 'Sonora', 'Code' => 'SON'],
            ['Name' => 'Tabasco', 'Code' => 'TAB'],
            ['Name' => 'Tamaulipas', 'Code' => 'TAMPS'],
            ['Name' => 'Tlaxcala', 'Code' => 'TLAX'],
            ['Name' => 'Veracruz', 'Code' => 'VER'],
            ['Name' => 'Yucatán', 'Code' => 'YUC'],
            ['Name' => 'Zacatecas', 'Code' => 'ZAC'],
        ],
        'TH' => [
            ['Name' => 'Amnat Charoen', 'Code' => 'Amnat Charoen'],
            ['Name' => 'Ang Thong', 'Code' => 'Ang Thong'],
            ['Name' => 'Bangkok', 'Code' => 'Bangkok'],
            ['Name' => 'Bueng Kan', 'Code' => 'Bueng Kan'],
            ['Name' => 'Buri Ram', 'Code' => 'Buri Ram'],
            ['Name' => 'Chachoengsao', 'Code' => 'Chachoengsao'],
            ['Name' => 'Chai Nat', 'Code' => 'Chai Nat'],
            ['Name' => 'Chaiyaphum', 'Code' => 'Chaiyaphum'],
            ['Name' => 'Chanthaburi', 'Code' => 'Chanthaburi'],
            ['Name' => 'Chiang Mai', 'Code' => 'Chiang Mai'],
            ['Name' => 'Chiang Rai', 'Code' => 'Chiang Rai'],
            ['Name' => 'Chon Buri', 'Code' => 'Chon Buri'],
            ['Name' => 'Chumphon', 'Code' => 'Chumphon'],
            ['Name' => 'Kalasin', 'Code' => 'Kalasin'],
            ['Name' => 'Kamphaeng Phet', 'Code' => 'Kamphaeng Phet'],
            ['Name' => 'Kanchanaburi', 'Code' => 'Kanchanaburi'],
            ['Name' => 'Khon Kaen', 'Code' => 'Khon Kaen'],
            ['Name' => 'Krabi', 'Code' => 'Krabi'],
            ['Name' => 'Lampang', 'Code' => 'Lampang'],
            ['Name' => 'Lamphun', 'Code' => 'Lamphun'],
            ['Name' => 'Loei', 'Code' => 'Loei'],
            ['Name' => 'Lop Buri', 'Code' => 'Lop Buri'],
            ['Name' => 'Mae Hong Son', 'Code' => 'Mae Hong Son'],
            ['Name' => 'Maha Sarakham', 'Code' => 'Maha Sarakham'],
            ['Name' => 'Mukdahan', 'Code' => 'Mukdahan'],
            ['Name' => 'Nakhon Nayok', 'Code' => 'Nakhon Nayok'],
            ['Name' => 'Nakhon Pathom', 'Code' => 'Nakhon Pathom'],
            ['Name' => 'Nakhon Phanom', 'Code' => 'Nakhon Phanom'],
            ['Name' => 'Nakhon Ratchasima', 'Code' => 'Nakhon Ratchasima'],
            ['Name' => 'Nakhon Sawan', 'Code' => 'Nakhon Sawan'],
            ['Name' => 'Nakhon Si Thammarat', 'Code' => 'Nakhon Si Thammarat'],
            ['Name' => 'Nan', 'Code' => 'Nan'],
            ['Name' => 'Narathiwat', 'Code' => 'Narathiwat'],
            ['Name' => 'Nong Bua Lamphu', 'Code' => 'Nong Bua Lamphu'],
            ['Name' => 'Nong Khai', 'Code' => 'Nong Khai'],
            ['Name' => 'Nonthaburi', 'Code' => 'Nonthaburi'],
            ['Name' => 'Pathum Thani', 'Code' => 'Pathum Thani'],
            ['Name' => 'Pattani', 'Code' => 'Pattani'],
            ['Name' => 'Phang Nga', 'Code' => 'Phang Nga'],
            ['Name' => 'Phatthalung', 'Code' => 'Phatthalung'],
            ['Name' => 'Phatthaya', 'Code' => 'Phatthaya'],
            ['Name' => 'Phayao', 'Code' => 'Phayao'],
            ['Name' => 'Phetchabun', 'Code' => 'Phetchabun'],
            ['Name' => 'Phetchaburi', 'Code' => 'Phetchaburi'],
            ['Name' => 'Phichit', 'Code' => 'Phichit'],
            ['Name' => 'Phitsanulok', 'Code' => 'Phitsanulok'],
            ['Name' => 'Phra Nakhon Si Ayutthaya', 'Code' => 'Phra Nakhon Si Ayutthaya'],
            ['Name' => 'Phrae', 'Code' => 'Phrae'],
            ['Name' => 'Phuket', 'Code' => 'Phuket'],
            ['Name' => 'Prachin Buri', 'Code' => 'Prachin Buri'],
            ['Name' => 'Prachuap Khiri Khan', 'Code' => 'Prachuap Khiri Khan'],
            ['Name' => 'Ranong', 'Code' => 'Ranong'],
            ['Name' => 'Ratchaburi', 'Code' => 'Ratchaburi'],
            ['Name' => 'Rayong', 'Code' => 'Rayong'],
            ['Name' => 'Roi Et', 'Code' => 'Roi Et'],
            ['Name' => 'Sa Kaeo', 'Code' => 'Sa Kaeo'],
            ['Name' => 'Sakon Nakhon', 'Code' => 'Sakon Nakhon'],
            ['Name' => 'Samut Prakan', 'Code' => 'Samut Prakan'],
            ['Name' => 'Samut Sakhon', 'Code' => 'Samut Sakhon'],
            ['Name' => 'Samut Songkhram', 'Code' => 'Samut Songkhram'],
            ['Name' => 'Saraburi', 'Code' => 'Saraburi'],
            ['Name' => 'Satun', 'Code' => 'Satun'],
            ['Name' => 'Si Sa Ket', 'Code' => 'Si Sa Ket'],
            ['Name' => 'Sing Buri', 'Code' => 'Sing Buri'],
            ['Name' => 'Songkhla', 'Code' => 'Songkhla'],
            ['Name' => 'Sukhothai', 'Code' => 'Sukhothai'],
            ['Name' => 'Suphan Buri', 'Code' => 'Suphan Buri'],
            ['Name' => 'Surat Thani', 'Code' => 'Surat Thani'],
            ['Name' => 'Surin', 'Code' => 'Surin'],
            ['Name' => 'Tak', 'Code' => 'Tak'],
            ['Name' => 'Trang', 'Code' => 'Trang'],
            ['Name' => 'Trat', 'Code' => 'Trat'],
            ['Name' => 'Ubon Ratchathani', 'Code' => 'Ubon Ratchathani'],
            ['Name' => 'Udon Thani', 'Code' => 'Udon Thani'],
            ['Name' => 'Uthai Thani', 'Code' => 'Uthai Thani'],
            ['Name' => 'Uttaradit', 'Code' => 'Uttaradit'],
            ['Name' => 'Yala', 'Code' => 'Yala'],
            ['Name' => 'Yasothon', 'Code' => 'Yasothon'],
        ],
        'US' => [
            ['Name' => 'Alabama', 'Code' => 'AL'],
            ['Name' => 'Alaska', 'Code' => 'AK'],
            ['Name' => 'Arizona', 'Code' => 'AZ'],
            ['Name' => 'Arkansas', 'Code' => 'AR'],
            ['Name' => 'California', 'Code' => 'CA'],
            ['Name' => 'Colorado', 'Code' => 'CO'],
            ['Name' => 'Connecticut', 'Code' => 'CT'],
            ['Name' => 'Delaware', 'Code' => 'DE'],
            ['Name' => 'District of Columbia', 'Code' => 'DC'],
            ['Name' => 'Florida', 'Code' => 'FL'],
            ['Name' => 'Georgia', 'Code' => 'GA'],
            ['Name' => 'Hawaii', 'Code' => 'HI'],
            ['Name' => 'Idaho', 'Code' => 'ID'],
            ['Name' => 'Illinois', 'Code' => 'IL'],
            ['Name' => 'Indiana', 'Code' => 'IN'],
            ['Name' => 'Iowa', 'Code' => 'IA'],
            ['Name' => 'Kansas', 'Code' => 'KS'],
            ['Name' => 'Kentucky', 'Code' => 'KY'],
            ['Name' => 'Louisiana', 'Code' => 'LA'],
            ['Name' => 'Maine', 'Code' => 'ME'],
            ['Name' => 'Maryland', 'Code' => 'MD'],
            ['Name' => 'Massachusetts', 'Code' => 'MA'],
            ['Name' => 'Michigan', 'Code' => 'MI'],
            ['Name' => 'Minnesota', 'Code' => 'MN'],
            ['Name' => 'Mississippi', 'Code' => 'MS'],
            ['Name' => 'Missouri', 'Code' => 'MO'],
            ['Name' => 'Montana', 'Code' => 'MT'],
            ['Name' => 'Nebraska', 'Code' => 'NE'],
            ['Name' => 'Nevada', 'Code' => 'NV'],
            ['Name' => 'New Hampshire', 'Code' => 'NH'],
            ['Name' => 'New Jersey', 'Code' => 'NJ'],
            ['Name' => 'New Mexico', 'Code' => 'NM'],
            ['Name' => 'New York', 'Code' => 'NY'],
            ['Name' => 'North Carolina', 'Code' => 'NC'],
            ['Name' => 'North Dakota', 'Code' => 'ND'],
            ['Name' => 'Ohio', 'Code' => 'OH'],
            ['Name' => 'Oklahoma', 'Code' => 'OK'],
            ['Name' => 'Oregon', 'Code' => 'OR'],
            ['Name' => 'Pennsylvania', 'Code' => 'PA'],
            ['Name' => 'Puerto Rico', 'Code' => 'PR'],
            ['Name' => 'Rhode Island', 'Code' => 'RI'],
            ['Name' => 'South Carolina', 'Code' => 'SC'],
            ['Name' => 'South Dakota', 'Code' => 'SD'],
            ['Name' => 'Tennessee', 'Code' => 'TN'],
            ['Name' => 'Texas', 'Code' => 'TX'],
            ['Name' => 'Utah', 'Code' => 'UT'],
            ['Name' => 'Vermont', 'Code' => 'VT'],
            ['Name' => 'Virginia', 'Code' => 'VA'],
            ['Name' => 'Washington', 'Code' => 'WA'],
            ['Name' => 'West Virginia', 'Code' => 'WV'],
            ['Name' => 'Wisconsin', 'Code' => 'WI'],
            ['Name' => 'Wyoming', 'Code' => 'WY'],

            ['Name' => 'Armed Forces APO', 'Code' => '--'],
            ['Name' => 'Armed Forces Americas', 'Code' => 'AA'],
            ['Name' => 'Armed Forces Europe', 'Code' => 'AE'],
            ['Name' => 'Armed Forces Pacific', 'Code' => 'AP'],

            ['Name' => 'Outlying Areas', 'Code' => '--'],
            ['Name' => 'American Samoa', 'Code' => 'AS'],
            ['Name' => 'Federated States of Micronesia', 'Code' => 'FM'],
            ['Name' => 'Guam', 'Code' => 'GU'],
            ['Name' => 'Marshall Islands', 'Code' => 'MH'],
            ['Name' => 'Northern Mariana Islands', 'Code' => 'MP'],
            ['Name' => 'Palau', 'Code' => 'PW'],
            ['Name' => 'Virgin Islands', 'Code' => 'VI'],
        ],
    ];

    public static function getStates(string $countryCode): ?array
    {
        if (array_key_exists($countryCode, self::$data)) return self::$data[$countryCode];
        return null;
    }
}
